const SITE_CONFIG = {
  title: "Northshore Cadet Learning Center",
  subtitle: "PCR-WA-068 | Civil Air Patrol",
  reviewDate: "2026-09-18",
  passingScore: 80,
  leadership: [
    { level: "Squadron", organization: "Northshore Composite Squadron · PCR-WA-068", position: "Squadron Commander", name: "Confirm with squadron staff", note: "Local leadership changes. Update this value after staff review." },
    { level: "Group", organization: "Northwest Group · Washington Wing", position: "Group Commander", name: "Confirm with WA Wing", note: "Northshore is listed in Northwest Group on the WA Wing locations page." },
    { level: "Wing", organization: "Washington Wing", position: "Wing Commander", name: "Confirm with WA Wing", note: "Use the current official Washington Wing directory." },
    { level: "Region", organization: "Pacific Region", position: "Region Commander", name: "Confirm with Pacific Region", note: "Use the current official region leadership page." },
    { level: "National", organization: "Civil Air Patrol National Headquarters", position: "National Commander", name: "Confirm with CAP NHQ", note: "Use CAP's current command team page." }
  ]
};

const RESOURCES = [
  { title: "CAPR 39-1", subtitle: "Civil Air Patrol Uniform Regulation", category: "Uniforms", url: "https://www.gocivilairpatrol.com/members/publications/indexes-regulations-and-manuals-1700", note: "Open the publication index for the regulation plus all attached interim change letters." },
  { title: "CAPR 60-1", subtitle: "Cadet Program Management", category: "Cadet Program", url: "https://www.gocivilairpatrol.com/members/publications/indexes-regulations-and-manuals-1700", note: "The governing regulation for cadet program administration and advancement." },
  { title: "CAPR 60-2", subtitle: "Cadet Protection Program", category: "Cadet Program", url: "https://www.gocivilairpatrol.com/members/publications/indexes-regulations-and-manuals-1700", note: "Official cadet protection policy and program requirements." },
  { title: "CAPR 30-1", subtitle: "Organization of Civil Air Patrol", category: "Organization", url: "https://www.gocivilairpatrol.com/members/publications/indexes-regulations-and-manuals-1700", note: "Current organization regulation. CAPR 20-1 now covers the Inspector General program." },
  { title: "CAPP 60-33", subtitle: "Drill & Ceremonies", category: "Drill", url: "https://www.gocivilairpatrol.com/programs/cadets/library/drill", note: "Official CAP drill and ceremonies reference." },
  { title: "CAPP 60-34", subtitle: "Drill & Ceremonies Practical Tests", category: "Drill", url: "https://www.gocivilairpatrol.com/programs/cadets/library/drill", note: "Current practical tests, including the Wright Brothers drill performance test." },
  { title: "Cadet Super Chart", subtitle: "Cadet advancement at a glance", category: "Promotions", url: "https://www.gocivilairpatrol.com/members/publications/visual-aids", note: "Use the current chart for exact achievement requirements and minimum eligibility dates." },
  { title: "CAP History", subtitle: "Official history of Civil Air Patrol", category: "History", url: "https://www.gocivilairpatrol.com/about/history-of-civil-air-patrol", note: "National Headquarters overview of CAP's origins and wartime service." },
  { title: "Cadet Character Resources", subtitle: "Core Values and character development", category: "Core Values", url: "https://www.gocivilairpatrol.com/programs/cadets/library/character", note: "Official materials for CAP's character program." },
  { title: "OCP Information", subtitle: "Operational Camouflage Pattern uniform", category: "Uniforms", url: "https://www.gocivilairpatrol.com/news/from-the-national-commander/ocp", note: "Official implementation letter and FAQ. The page says the regulation and ICL control." },
  { title: "Washington Wing", subtitle: "Units and wing information", category: "Local", url: "https://wawg.cap.gov/", note: "Official Washington Wing website." },
  { title: "Northshore Composite Squadron", subtitle: "PCR-WA-068", category: "Local", url: "https://northshore.cap.gov/", note: "Official squadron website." }
];

const GLOSSARY = [
  ["Aerospace Education", "One of CAP's three primary missions; it promotes understanding of aviation, space, cyber, and STEM."],
  ["Blues", "Common informal name for the Air Force-style service uniform combinations authorized by CAPR 39-1."],
  ["C/A1C", "Cadet Airman First Class."], ["C/Amn", "Cadet Airman."], ["C/SSgt", "Cadet Staff Sergeant, the first cadet NCO grade."], ["C/SrA", "Cadet Senior Airman."],
  ["Cadet", "A CAP member participating in the Cadet Program, generally from age 12 through 20."],
  ["Cadet Programs", "One of CAP's three primary missions; it develops youth through leadership, aerospace, fitness, and character."],
  ["CAP", "Civil Air Patrol, the congressionally chartered nonprofit corporation that serves as the civilian auxiliary of the U.S. Air Force when assigned."],
  ["Chain of Command", "The orderly line through which authority and responsibility pass."], ["COC", "Common abbreviation for chain of command."],
  ["Core Values", "Integrity, Volunteer Service, Excellence, and Respect."],
  ["Emergency Services", "One of CAP's three primary missions, including disaster relief, search and rescue, and support to communities and agencies."],
  ["Encampment", "A structured cadet activity emphasizing leadership, aerospace, fitness, teamwork, and the CAP environment."],
  ["Grade", "A member's rank, such as Cadet Airman or Captain; it is different from a duty position."],
  ["Group", "An intermediate echelon that may coordinate several squadrons within a wing."], ["NCO", "Noncommissioned officer."], ["NHQ", "Civil Air Patrol National Headquarters."],
  ["OCP", "Operational Camouflage Pattern, the currently authorized Air Force-style utility uniform addressed by CAPR 39-1 and its interim changes."],
  ["Region", "An organizational echelon that coordinates multiple wings."], ["Senior Member", "An adult CAP member serving outside the cadet membership category."],
  ["Squadron", "A local CAP unit where members normally meet and train."], ["Wing", "An organizational echelon generally corresponding to a state, the District of Columbia, or Puerto Rico."]
].map(([term, definition]) => ({ term, definition }));

const MODULES = [
  {
    id: "history", number: "01", title: "History of Civil Air Patrol", icon: "1941", time: "10 min",
    description: "Why CAP was created, its World War II service, and the organization's modern missions.",
    sections: [
      { title: "Why CAP was created", kicker: "Origins · 1941", body: ["Civil Air Patrol was established on December 1, 1941, just days before the United States entered World War II. Civilian aviation advocates had argued that private pilots and aircraft could contribute to national defense.", "Volunteers brought their aircraft, flying skills, and local knowledge. CAP members performed patrol, courier, transport, training, and other support missions while the armed forces concentrated on combat operations."], takeaway: "CAP began as citizens using aviation skills in service to the nation." },
      { title: "Coastal Patrol", kicker: "Wartime service", body: ["German submarines threatened shipping along the Atlantic and Gulf coasts. CAP coastal patrol crews flew from a network of bases to watch for submarines, survivors, and ships in distress.", "Some CAP aircraft were eventually authorized to carry bombs or depth charges. Their presence helped deter submarine activity, and the patrols demonstrated how organized civilian aviation could support national defense."], takeaway: "CAP coastal patrol was one part of a broader wartime support effort." },
      { title: "From war to auxiliary", kicker: "1946–1948", body: ["Congress granted Civil Air Patrol a federal charter in 1946. In 1948, Congress designated CAP as the civilian auxiliary of the newly created United States Air Force.", "Those actions helped move CAP from a temporary wartime organization to an enduring public-service institution. CAP remains a nonprofit corporation and serves as the Air Force auxiliary when assigned an Air Force mission."], takeaway: "CAP's postwar legal status shaped the organization cadets know today." },
      { title: "CAP today", kicker: "Three primary missions", body: ["Emergency Services supports communities and government partners through missions such as disaster relief, search and rescue, and aerial imagery.", "Aerospace Education advances aviation, space, cyber, and STEM learning. Cadet Programs develops young people through leadership, aerospace, fitness, character, and service."], cards: [["Emergency Services", "Ready communities and trained volunteer response."], ["Aerospace Education", "Aviation, space, cyber, and STEM learning."], ["Cadet Programs", "Leadership and character development for youth."]], takeaway: "The three missions reinforce one another through service, learning, and leadership." }
    ],
    activity: { type: "timeline", title: "Mission timeline", items: [["1941", "CAP established", "Civil Air Patrol is established on December 1."], ["1942", "Coastal Patrol", "CAP begins coastal patrol operations during World War II."], ["1946", "Federal charter", "Congress grants CAP a federal charter."], ["1948", "Air Force auxiliary", "Congress designates CAP as the civilian auxiliary of the U.S. Air Force."], ["Today", "Three missions", "Emergency Services, Aerospace Education, and Cadet Programs."]] },
    sources: ["CAP History"],
    quiz: [
      { q: "When was Civil Air Patrol established?", options: ["December 1, 1941", "July 4, 1946", "September 18, 1947", "May 26, 1948"], answer: 0, why: "CAP was established on December 1, 1941." },
      { q: "What threat was a major focus of CAP coastal patrol?", options: ["Forest fires", "German submarines", "Airport congestion", "Weather balloons"], answer: 1, why: "Coastal patrol crews watched for German U-boats, survivors, and ships in distress." },
      { q: "Which event happened first?", options: ["CAP became the Air Force auxiliary", "CAP received a federal charter", "The Wright Brothers Award began", "OCP wear was authorized"], answer: 1, why: "CAP received its federal charter in 1946 and became the Air Force auxiliary in 1948." },
      { q: "Which list contains CAP's three primary missions?", options: ["Flying, drill, and uniforms", "Emergency Services, Aerospace Education, and Cadet Programs", "Search, rescue, and transport", "Leadership, fitness, and character"], answer: 1, why: "CAP organizes its work around Emergency Services, Aerospace Education, and Cadet Programs." },
      { q: "True or false: CAP's World War II service was limited only to coastal patrol.", options: ["True", "False"], answer: 1, why: "CAP volunteers performed several kinds of support work, including courier, transport, training, patrol, and other missions." }
    ]
  },
  {
    id: "core-values", number: "02", title: "Core Values & Cadet Oath", icon: "IVXE", time: "15 min",
    description: "Practice Integrity, Volunteer Service, Excellence, and Respect—and understand every promise in the oath.",
    sections: [
      { title: "Integrity", kicker: "Do what is right", body: ["Integrity means choosing honesty and moral courage even when no one is watching. A cadet reports mistakes, protects test integrity, and can be trusted with equipment and responsibility.", "Example: You accidentally damage squadron equipment. Report it promptly, explain what happened, and help make it right. Hiding the damage violates integrity."], takeaway: "Truthful accountability builds trust." },
      { title: "Volunteer Service", kicker: "Put service before self", body: ["Volunteer Service means willingly giving time, talent, and effort to help the team and community. It does not require ignoring safety or personal limits; it means looking beyond convenience.", "Example: Arrive prepared, help reset the meeting space, and assist a new cadet without waiting to be asked. Avoid taking credit for work you did not do."], takeaway: "Service asks: what does the mission need from me?" },
      { title: "Excellence", kicker: "Improve the standard", body: ["Excellence is a habit of disciplined improvement. It is not perfection. It means preparing carefully, learning from feedback, and completing duties to the best standard you can reach.", "Example: Practice drill before a performance and correct a recurring mistake. Rushing through a task because it is 'good enough' does not demonstrate excellence."], takeaway: "Prepare, perform, review, improve." },
      { title: "Respect", kicker: "Value every person", body: ["Respect means treating people with dignity and fairness. Courtesy, listening, professional language, and care for boundaries all show respect—regardless of grade or position.", "Example: Correct a teammate privately and constructively. Humiliating someone, hazing, or dismissing a concern violates respect."], takeaway: "Standards and dignity belong together." },
      { title: "The Cadet Oath", kicker: "A promise with actions", oath: true, body: ["The oath is not simply something to memorize. Each phrase describes a commitment: faithful service, regular attendance, active participation, lawful obedience, proper uniform wear, rapid growth, and readiness to serve.", "Cadets should ask questions when an instruction is unclear or appears unsafe. Following the chain of command never removes the duty to act safely and ethically."], takeaway: "The oath turns CAP membership into a personal commitment to learn and serve." }
    ],
    activity: { type: "oath", title: "Explore the Cadet Oath", items: [["serve faithfully", "Be dependable and uphold the Cadet Program's purpose and values."], ["attend meetings regularly", "Show up consistently so your team can rely on you and your skills can grow."], ["participate actively", "Engage, ask questions, practice, and contribute—not merely occupy a seat."], ["obey my officers", "Follow lawful, safe instructions through the chain of command and seek clarification when needed."], ["wear my uniform properly", "Represent CAP professionally and use the current uniform regulation."], ["advance my education and training rapidly", "Take ownership of steady progress without sacrificing understanding or integrity."], ["be of service", "Prepare your skills and character to help your community, state, and nation."]] },
    sources: ["Cadet Character Resources", "CAPR 60-1"],
    quiz: [
      { q: "You damage squadron equipment and nobody sees it. Which action best demonstrates Integrity?", options: ["Put it back quietly", "Blame normal wear", "Report the damage and help make it right", "Wait to see if someone notices"], answer: 2, why: "Integrity includes truthful accountability even when admitting a mistake is uncomfortable." },
      { q: "Which Core Value is most directly shown by helping a new cadet learn without being asked?", options: ["Volunteer Service", "Excellence", "Integrity", "Respect only"], answer: 0, why: "Willingly contributing time and effort to help the team demonstrates Volunteer Service." },
      { q: "Excellence means never making a mistake.", options: ["True", "False"], answer: 1, why: "Excellence is disciplined preparation and improvement, not impossible perfection." },
      { q: "What is the difference between attending and participating actively?", options: ["There is no difference", "Active participation means engaging, practicing, and contributing", "Active participation means speaking the most", "Attendance matters only for promotion"], answer: 1, why: "The oath asks cadets to contribute to activities, not simply be present." },
      { q: "Which response best demonstrates Respect during a correction?", options: ["Embarrass the cadet so others learn", "Ignore the issue", "Correct privately, clearly, and constructively", "Use rank to end discussion"], answer: 2, why: "Respect preserves dignity while still supporting standards." }
    ]
  },
  {
    id: "chain-of-command", number: "03", title: "Chain of Command", icon: "COC", time: "10 min",
    description: "Follow Northshore's path from squadron to National Headquarters and learn when to use each chain.",
    sections: [
      { title: "Why a chain exists", kicker: "Authority + responsibility", body: ["A chain of command gives questions, decisions, and accountability an orderly route. Start with the lowest appropriate leader who can help, then move upward when needed.", "Urgent safety issues, cadet protection concerns, or situations covered by policy may require a different reporting route. Never delay immediate safety action just to preserve routine routing."], takeaway: "Use the chain to solve problems, not to hide them." },
      { title: "Cadet chain", kicker: "Leading cadets", body: ["The cadet chain connects cadet duty positions, such as element leader, flight sergeant, flight commander, and cadet commander. Exact positions depend on the unit's current organization.", "A duty position is a job; grade is rank. A Cadet Staff Sergeant may hold one of several jobs, and the same job can be reassigned as the unit develops leaders."], takeaway: "Ask the leader closest to the work first." },
      { title: "Senior member chain", kicker: "Adult command", body: ["The senior member chain leads the unit and is responsible for the cadet program, safety, supervision, and regulatory compliance. The squadron commander remains responsible for the squadron even when cadets lead cadet activities.", "Cadet leaders train and lead within authority delegated by senior members. Cadets can always bring safety or welfare concerns to an appropriate senior member."], takeaway: "Cadet leadership operates within senior-member oversight." },
      { title: "Organizational chain", kicker: "Squadron to NHQ", body: ["Northshore Composite Squadron is a local unit in Northwest Group, Washington Wing, Pacific Region, and Civil Air Patrol nationally.", "Groups coordinate assigned units where a wing uses them; wings organize CAP within their jurisdiction; regions coordinate wings; National Headquarters supports CAP-wide policy, programs, and administration."], takeaway: "Each echelon coordinates a wider area and set of responsibilities." }
    ],
    activity: { type: "hierarchy", title: "Explore Northshore's organizational path", items: SITE_CONFIG.leadership.map((x) => [x.level, x.organization, x.note]) },
    sources: ["CAPR 30-1", "Washington Wing", "Northshore Composite Squadron"],
    quiz: [
      { q: "Put the organizational levels in order from local to national.", options: ["Squadron → Group → Wing → Region → National", "Squadron → Wing → Group → National → Region", "Group → Squadron → Region → Wing → National", "Squadron → Region → Wing → Group → National"], answer: 0, why: "Northshore's path is Squadron, Northwest Group, Washington Wing, Pacific Region, then National Headquarters." },
      { q: "What is the best first step for a routine question about tonight's assigned task?", options: ["Contact National Headquarters", "Ask the lowest appropriate leader in your chain", "Post the question publicly", "Skip the task"], answer: 1, why: "Routine issues should normally begin with the leader closest to the work." },
      { q: "Grade and duty position mean the same thing.", options: ["True", "False"], answer: 1, why: "Grade is rank; duty position is the job a member currently performs." },
      { q: "Which echelon normally corresponds to a state?", options: ["Squadron", "Group", "Wing", "Region"], answer: 2, why: "A wing generally organizes CAP units within a state or comparable jurisdiction." },
      { q: "Should a cadet delay reporting an urgent safety problem to preserve the routine chain?", options: ["Yes", "No"], answer: 1, why: "Immediate safety and protection concerns should use the appropriate direct route without unnecessary delay." }
    ]
  },
  {
    id: "customs", number: "04", title: "Customs & Courtesies", icon: "SAL", time: "15 min",
    description: "Build confident habits for saluting, forms of address, reporting, formations, and ceremonies.",
    sections: [
      { title: "Saluting", kicker: "Recognition and respect", body: ["The salute is a professional exchange of respect. Cadets salute commissioned officers when outdoors and in the appropriate uniform, unless a situation or formation procedure makes the salute inappropriate.", "When recognition is uncertain, use good judgment and professional courtesy. The detailed rules and special situations are in CAP's drill and ceremonies publications; local leaders can demonstrate the standard."], takeaway: "Recognize, salute smartly, and offer the greeting of the day." },
      { title: "Flags and anthem", kicker: "Ceremonial respect", body: ["During outdoor ceremonies, members follow the commands and formation procedures for honors to the U.S. flag and the national anthem. Individuals not in formation face the flag—or the music when the flag is not visible—and render the salute when prescribed.", "Indoor and outdoor procedures, uniform status, and formation context can change the required action. Learn the full sequence from CAPP 60-33 and supervised practice."], takeaway: "Pause, face the proper direction, and follow the ceremony's commands." },
      { title: "Forms of address", kicker: "Grade is not position", body: ["Use grade and last name when known, or Sir/Ma'am for officers as appropriate. Cadet Airmen, cadet NCOs, cadet officers, senior member NCOs, and senior member officers should be addressed professionally.", "A person's duty position identifies the job; grade identifies rank. 'Cadet Commander' is a position. 'Cadet Captain' is a grade."], takeaway: "When in doubt, be professional and ask how the member should be addressed." },
      { title: "Reporting", kicker: "A deliberate sequence", body: ["Reporting procedures vary with setting and whether you are indoors, outdoors, or in formation. A common office sequence is to knock once if appropriate, enter when directed, approach and halt about two paces away, salute when required, make the reporting statement, remain until dismissed, and salute before departing when appropriate.", "Use the exact sequence your instructor demonstrates from current CAP drill guidance. The purpose is clear, disciplined communication—not theater."], steps: ["Knock if appropriate", "Enter when directed", "Approach and halt", "Salute when required", "State the reporting message", "Remain until dismissed", "Salute and depart when appropriate"], takeaway: "Practice the sequence slowly, then build confidence." }
    ],
    activity: { type: "scenario", title: "Saluting scenario trainer", prompt: "You are outdoors in uniform. A CAP captain approaches and neither of you is in formation. What is the best response?", options: ["Ignore the officer", "Salute and give the greeting of the day", "Stand at parade rest", "Remove your cover"], answer: 1, feedback: "Salute the officer and offer an appropriate greeting. Keep moving unless the situation calls for you to stop." },
    sources: ["CAPP 60-33", "CAPR 60-1"],
    quiz: [
      { q: "You are walking outdoors in uniform and a CAP captain approaches. What should you normally do?", options: ["Ignore them", "Salute and offer the greeting of the day", "Remove your cover", "Stand at parade rest"], answer: 1, why: "Cadets normally exchange salutes with commissioned officers outdoors when the situation is appropriate." },
      { q: "Which is a duty position rather than a grade?", options: ["Cadet Captain", "Captain", "Cadet Commander", "Cadet Staff Sergeant"], answer: 2, why: "Cadet Commander describes a job. The other choices are grades." },
      { q: "When the U.S. flag is not visible during an outdoor anthem, what direction is generally used?", options: ["Face north", "Face the music", "Face the nearest officer", "Remain facing forward in every situation"], answer: 1, why: "Individuals generally face the music when the flag is not visible, while following formation commands if in formation." },
      { q: "About how far from an officer does the common office-reporting sequence call for halting?", options: ["One arm's length", "About two paces", "Ten paces", "At the doorway"], answer: 1, why: "The common sequence uses approximately two paces; practice the exact procedure with an instructor." },
      { q: "Which source should control detailed CAP drill and ceremonial procedures?", options: ["A social media clip", "CAPP 60-33 and current official guidance", "A movie", "An unofficial forum"], answer: 1, why: "Use current official CAP publications and supervised instruction." }
    ]
  },
  {
    id: "promotions", number: "05", title: "Cadet Promotions", icon: "↑", time: "15 min",
    description: "Explore the Phase I progression from Cadet Airman Basic through the Wright Brothers Award.",
    sections: [
      { title: "Phase I: The Learning Phase", kicker: "Build foundations", body: ["Phase I introduces followership, self-discipline, CAP knowledge, drill, fitness, character, and aerospace. New cadets begin as Cadet Airman Basic and advance by completing achievement requirements and demonstrating readiness for greater responsibility.", "Promotion is more than passing online tests. Participation, performance, character, fitness, drill, and command approval all matter under the current cadet program rules."], takeaway: "Own your progress and ask staff which requirement comes next." },
      { title: "Curry Achievement", kicker: "Achievement 1 · C/Amn", body: ["The Curry Achievement is named for Maj Gen John F. Curry, CAP's first national commander. Completion earns the grade of Cadet Airman and marks the first promotion.", "Typical categories include introductory leadership learning, character participation, fitness participation, active participation, the Cadet Oath, and the required drill performance. Confirm the current checklist in the Cadet Super Chart and eServices."], takeaway: "Curry proves you can begin building reliable cadet habits." },
      { title: "Arnold & Feik", kicker: "Achievements 2–3", body: ["The Arnold Achievement honors Gen Henry H. 'Hap' Arnold and leads to Cadet Airman First Class. The Feik Achievement honors aviation pioneer and CAP leader Mary Feik and leads to Cadet Senior Airman.", "Each achievement continues leadership, aerospace, character, fitness, drill, active participation, and time-in-grade requirements as shown on the current Super Chart. Exact test modules and standards can change, so verify before planning."], takeaway: "Phase I alternates learning, practice, and increasing responsibility." },
      { title: "Wright Brothers Award", kicker: "Milestone · C/SSgt", body: ["The Wright Brothers Award marks completion of Phase I and promotion to Cadet Staff Sergeant when all current requirements are completed and the promotion is approved.", "It includes controlled milestone testing and a drill and ceremonies performance component. Milestone exams are administered through the squadron under current CAP procedures. The award also opens Phase II, where cadets begin serving as NCOs and leading teams."], takeaway: "The first milestone marks the shift from learning followership to practicing NCO leadership." }
    ],
    activity: { type: "ladder", title: "Phase I promotion ladder", items: [["C/AB", "Cadet Airman Basic", "Starting grade"], ["C/Amn", "Curry Achievement", "Achievement 1"], ["C/A1C", "Arnold Achievement", "Achievement 2"], ["C/SrA", "Feik Achievement", "Achievement 3"], ["C/SSgt", "Wright Brothers Award", "Phase I milestone"]] },
    sources: ["Cadet Super Chart", "CAPR 60-1", "CAPP 60-34"],
    quiz: [
      { q: "Which achievement normally results in promotion to Cadet Airman?", options: ["Arnold", "Curry", "Feik", "Wright Brothers"], answer: 1, why: "Achievement 1, named for Maj Gen John F. Curry, leads to Cadet Airman." },
      { q: "Which achievement is associated with Cadet Senior Airman?", options: ["Curry", "Arnold", "Feik", "Wright Brothers"], answer: 2, why: "The Feik Achievement is the third Phase I achievement and leads to Cadet Senior Airman." },
      { q: "What does the Wright Brothers Award mark?", options: ["Joining CAP", "Completion of Phase I and promotion to C/SSgt when requirements are met", "Completion of encampment", "Becoming a cadet officer"], answer: 1, why: "The Wright Brothers milestone completes Phase I and begins cadet NCO service." },
      { q: "Passing online tests is the only requirement for promotion.", options: ["True", "False"], answer: 1, why: "The program also considers participation, drill, fitness, character, performance, and approval under current rules." },
      { q: "Where should a cadet check exact current achievement requirements?", options: ["An old handout", "The current Cadet Super Chart, eServices, and CAPR 60-1", "A social post", "A uniform catalog"], answer: 1, why: "Official current sources control because requirements and materials can change." }
    ]
  },
  {
    id: "grooming", number: "06", title: "Hair & Grooming", icon: "39-1", time: "10 min",
    description: "Learn how to find and apply current CAPR 39-1 grooming standards without relying on outdated rules.",
    sections: [
      { title: "Start with the right rule", kicker: "CAPR 39-1 + ICLs", body: ["Grooming rules depend on the uniform category, and CAPR 39-1 may be supplemented by interim change letters. Open the current publication index before relying on a measurement or an older checklist.", "This training module intentionally does not repeat numerical limits without a verified paragraph. Ask staff to review the current text and illustrations with you."], takeaway: "Never turn a remembered number into a regulation." },
      { title: "Masculine standards", kicker: "Professional appearance", body: ["Review the current provisions for hair appearance, bulk, length, tapered appearance, contact with ears or collar, sideburns, mustaches, and other facial hair.", "The standard is more specific than simply 'neat.' Use the current paragraph and figures, especially when a question involves measurement, medical or religious accommodation, or a style not clearly shown."], takeaway: "Use the published standard, not personal preference." },
      { title: "Feminine standards", kicker: "Professional appearance", body: ["Review the current provisions for hair length, bulk, bangs, ponytails, braids, buns, accessories, and styles worn in uniform. Authorized options and exact limits may be updated by interim change.", "Hair must also allow required headgear and safety equipment to be worn correctly. Use CAPR 39-1 and current changes rather than assuming another service's rule automatically applies."], takeaway: "A professional result can include multiple authorized styles." },
      { title: "Color, accessories, and judgment", kicker: "Consistent and mission-ready", body: ["Hair color, accessories, cosmetics, nails, jewelry, and related appearance topics are addressed by uniform category and current policy. Conservative or professional wording is not permission to invent local measurements.", "Leaders should correct standards consistently, privately, and respectfully. Cadets should ask for the source paragraph when a rule is unclear."], takeaway: "Cite the rule and preserve dignity during corrections." }
    ],
    activity: { type: "checklist", title: "Grooming standard finder", items: [["Hair shape and bulk", "Find the paragraph for your uniform category; verify any current ICL."], ["Ears, collar, and taper", "Use the exact text and figures rather than a remembered rule."], ["Ponytails, braids, and buns", "Confirm style, length, bulk, accessory, and headgear provisions."], ["Sideburns and facial hair", "Check the current grooming section and any accommodation policy."], ["Color and accessories", "Confirm authorized colors, size limits, and placement in the current publication."]] },
    sources: ["CAPR 39-1", "OCP Information"],
    quiz: [
      { q: "Where should you verify a numerical grooming limit?", options: ["A friend's memory", "The current CAPR 39-1 paragraph and attached changes", "A recruiting poster", "Any Air Force video"], answer: 1, why: "Exact limits must come from the current CAP publication and its interim changes." },
      { q: "CAP automatically adopts every Air Force grooming rule without CAP guidance.", options: ["True", "False"], answer: 1, why: "CAP members must follow CAP-authorized standards; do not assume another service's rule automatically applies." },
      { q: "What should a leader do when making a grooming correction?", options: ["Invent a stricter local limit", "Correct publicly", "Use the source, be consistent, and preserve dignity", "Ignore every issue"], answer: 2, why: "Accurate, respectful correction supports both standards and the Core Values." },
      { q: "Why should interim change letters be checked?", options: ["They may modify the base regulation", "They are only historical", "They are optional", "They apply only to pilots"], answer: 0, why: "An interim change letter can add or alter requirements before the base publication is rewritten." },
      { q: "Which factor can affect whether a hairstyle works in uniform?", options: ["Whether required headgear and safety equipment fit correctly", "Whether it is popular", "Whether another cadet wears it", "Whether it appears online"], answer: 0, why: "Uniform grooming must support correct wear of required headgear and mission equipment." }
    ]
  },
  {
    id: "uniforms", number: "07", title: "Uniform Regulations", icon: "UOD", time: "15 min",
    description: "Inspect Blues and OCP uniforms using the current regulation, figures, tables, and interim changes.",
    sections: [
      { title: "Uniform mindset", kicker: "Service, not costume", body: ["The uniform identifies you as a CAP member and communicates attention to detail. Wear only authorized items, in the authorized combination, and maintain a clean, serviceable appearance.", "CAPR 39-1, its attached interim change letters, and approved supplements control. Product photos, old handouts, and another service's habits do not replace them."], takeaway: "Check the whole uniform before focusing on one insignia." },
      { title: "Air Force-style service uniform", kicker: "Blues", body: ["Build the uniform from the authorized combination: correct shirt or blouse, trousers or skirt, belt, footwear, headgear when required, insignia, nameplate, ribbons or badges as authorized, and appropriate outerwear.", "Placement details vary by garment, grade, and item. Use the current CAPR 39-1 figures and tables for measurements. Cadets who do not yet have every optional item should prioritize the required, properly fitted basics."], takeaway: "Correct fit and placement are part of military professionalism." },
      { title: "Operational Camouflage Pattern", kicker: "OCP", body: ["CAP's OCP authorization is governed by CAPR 39-1 and the applicable interim change letter. Confirm the coat, trousers, patrol cap, Tan 499 shirt and belt, coyote-brown boots, authorized tapes, grade, and currently authorized patches.", "The official OCP FAQ is helpful but states that it is not regulatory. When the FAQ and a memory differ, return to the ICL and regulation. Do not mix incompatible uniform variants or attachment methods when current guidance prohibits it."], takeaway: "OCP details are changing—always check the latest official package." },
      { title: "Accessories and final inspection", kicker: "From headgear to footwear", body: ["Review headgear, outerwear, jewelry, watches, sunglasses, gloves, bags, and other accessories as part of the complete uniform. Authorization can depend on the uniform and setting.", "Use a consistent inspection: headgear; grooming; collar and insignia; tapes or nameplate; pockets and patches; belt; trousers; footwear; then authorized accessories. Ask a trained leader to verify anything uncertain."], takeaway: "A repeatable inspection sequence catches preventable errors." }
    ],
    activity: { type: "uniform", title: "What's wrong with this uniform?", prompt: "Select every item that should be verified before this notional OCP uniform is worn.", items: [["Name and CAP tapes", "Confirm required tapes, placement, color, and attachment method."], ["Grade insignia", "Confirm the correct grade, placement, and attachment method for the member."], ["Unit or higher-HQ patch", "Confirm the patch is currently authorized and approved for OCP wear."], ["Boots and belt", "Confirm coyote-brown boots and the current Tan 499 belt requirement."], ["Accessories", "Remove unauthorized items and verify any watch, eyewear, bag, or outerwear."]] },
    sources: ["CAPR 39-1", "OCP Information"],
    quiz: [
      { q: "Which source controls CAP uniform wear?", options: ["A vendor catalog", "CAPR 39-1 with current ICLs and approved supplements", "A movie", "Any Air Force checklist"], answer: 1, why: "Current CAP publications control CAP uniform wear." },
      { q: "The official OCP FAQ describes itself as regulatory.", options: ["True", "False"], answer: 1, why: "The FAQ says it is for reference and that the ICL and CAPR 39-1 control." },
      { q: "Which item belongs in a complete uniform inspection?", options: ["Only the shirt", "Only insignia", "Headgear through footwear plus authorized accessories", "Only the most visible error"], answer: 2, why: "A systematic head-to-toe check catches fit, placement, condition, and accessory issues." },
      { q: "May any squadron patch be placed on an OCP uniform?", options: ["Yes, every squadron patch is automatically authorized", "No; verify the patch is currently approved and authorized", "Only if it is colorful", "Only cadet officers may wear one"], answer: 1, why: "Current OCP guidance limits patches and requires applicable approval." },
      { q: "What should you do when an exact insignia measurement is uncertain?", options: ["Estimate", "Copy a friend", "Use the current CAPR 39-1 figure or table and ask staff", "Leave every insignia off"], answer: 2, why: "Exact placement should be verified from the current official illustration or text." }
    ]
  }
];
