const SITE_CONFIG = {
  title: "Northshore Cadet Learning Center",
  subtitle: "PCR-WA-068 | Civil Air Patrol",
  reviewDate: "2026-09-21",
  passingScore: 80,
  leadership: [
    { level: "National", organization: "Civil Air Patrol National Headquarters", position: "National Commander", name: "Maj Gen Regena M. Aye, CAP", note: "Verified on the CAP National Command Team page; re-check when national command changes." },
    { level: "Region", organization: "Pacific Region", position: "Region Commander", name: "Col Brett D. Dolnick, CAP", note: "Roster supplied by Northshore; verify against the current Pacific Region staff directory." },
    { level: "Wing", organization: "Washington Wing", position: "Wing Commander", name: "Col Sid Wiggs, CAP", note: "Verified on the Washington Wing Staff and Contacts page." },
    { level: "Group", organization: "Northwest Group · Washington Wing", position: "Group Commander", name: "Lt Col Thomas Wittenberg, CAP", note: "Roster supplied by Northshore; verify with the current group or wing directory." },
    { level: "Squadron", organization: "Northshore Composite Squadron · PCR-WA-068", position: "Squadron Commander", name: "Capt Carlos Jiminez, CAP", note: "Local roster supplied by Northshore; confirm after any change of command." },
    { level: "Squadron", organization: "Northshore Composite Squadron · PCR-WA-068", position: "Deputy Commander for Cadets", name: "Capt Daniel Taylor, CAP", note: "Local roster supplied by Northshore; confirm after staff changes." },
    { level: "Cadet Staff", organization: "Northshore Composite Squadron · PCR-WA-068", position: "Cadet Commander", name: "C/Capt Daniel Taylor, CAP", note: "Local cadet staff roster supplied by Northshore; cadet duty positions rotate." },
    { level: "Cadet Staff", organization: "Northshore Composite Squadron · PCR-WA-068", position: "Cadet Deputy Commander for Operations", name: "C/Capt Tieman Green, CAP", note: "Local cadet staff roster supplied by Northshore; cadet duty positions rotate." },
    { level: "Cadet Staff", organization: "Northshore Composite Squadron · PCR-WA-068", position: "Cadet Deputy Commander for Support", name: "C/Capt Kiyomi Hakuno, CAP", note: "Local cadet staff roster supplied by Northshore; cadet duty positions rotate." },
    { level: "Tango Flight", organization: "Northshore Composite Squadron · PCR-WA-068", position: "Tango Flight Commander", name: "C/SMSgt Liam Johnson, CAP", note: "Local cadet staff roster supplied by Northshore; flight assignments rotate." },
    { level: "Tango Flight", organization: "Northshore Composite Squadron · PCR-WA-068", position: "Tango Flight Sergeant", name: "C/MSgt Jason How, CAP", note: "Local cadet staff roster supplied by Northshore; flight assignments rotate." }
  ]
};

const RESOURCES = [
  { title: "CAPR 39-1", subtitle: "Civil Air Patrol Uniform Regulation", category: "Uniforms", url: "https://www.gocivilairpatrol.com/members/publications/indexes-regulations-and-manuals-1700", note: "Open the publication index for the regulation plus all attached interim change letters." },
  { title: "CAPR 60-1", subtitle: "Cadet Program Management", category: "Cadet Program", url: "https://www.gocivilairpatrol.com/members/publications/indexes-regulations-and-manuals-1700", note: "The governing regulation for cadet program administration and advancement." },
  { title: "CAPR 60-2", subtitle: "Cadet Protection Program", category: "Cadet Program", url: "https://www.gocivilairpatrol.com/members/publications/indexes-regulations-and-manuals-1700", note: "Official cadet protection policy and program requirements." },
  { title: "CAPR 30-1", subtitle: "Organization of Civil Air Patrol", category: "Organization", url: "https://www.gocivilairpatrol.com/members/publications/indexes-regulations-and-manuals-1700", note: "Current organization regulation. CAPR 20-1 now covers the Inspector General program." },
  { title: "CAPP 60-33", subtitle: "Drill & Ceremonies", category: "Drill", url: "https://www.gocivilairpatrol.com/programs/cadets/library/drill", note: "Official CAP drill and ceremonies reference." },
  { title: "CAPP 60-34", subtitle: "Drill & Ceremonies Practical Tests", category: "Drill", url: "https://www.gocivilairpatrol.com/programs/cadets/library/drill", note: "Current practical tests, including the Wright Brothers drill performance test." },
  { title: "Cadet Super Chart", subtitle: "Cadet advancement at a glance", category: "Promotions", url: "https://www.gocivilairpatrol.com/members/publications/visual-aids", note: "Use the current chart for exact achievement requirements and minimum eligibility dates." },
  { title: "CAP History", subtitle: "Official history of Civil Air Patrol", category: "History", url: "https://www.gocivilairpatrol.com/about/history-of-civil-air-patrol", note: "National Headquarters overview of CAP's origins and wartime service." },
  { title: "Cadet Character Resources", subtitle: "Core Values and character development", category: "Core Values", url: "https://www.gocivilairpatrol.com/programs/cadets/library/character", note: "Official materials for CAP's character program." },
  { title: "OCP Information", subtitle: "Operational Camouflage Pattern uniform", category: "Uniforms", url: "https://www.gocivilairpatrol.com/news/from-the-national-commander/ocp", note: "Official implementation letter and FAQ. The page says the regulation and ICL control." },
  { title: "Washington Wing", subtitle: "Units and wing information", category: "Local", url: "https://wawg.cap.gov/", note: "Official Washington Wing website." },
  { title: "Northshore Composite Squadron", subtitle: "PCR-WA-068", category: "Local", url: "https://northshore.cap.gov/", note: "Official squadron website." }
  ,{ title: "CAP National Command Team", subtitle: "Current national leadership", category: "Organization", url: "https://www.gocivilairpatrol.com/about/governance/cap-commandteam", note: "Official source for the National Commander and national command team." }
  ,{ title: "Pacific Region Staff", subtitle: "Current region leadership", category: "Organization", url: "https://pcr.cap.gov/about/pacific-region-staff/", note: "Official Pacific Region staff directory; re-check when leadership changes." }
  ,{ title: "Washington Wing Staff", subtitle: "Current wing leadership", category: "Organization", url: "https://wawg.cap.gov/about/staff-and-contacts", note: "Official Washington Wing staff and command directory." }
];

const GLOSSARY = [
  ["Aerospace Education", "One of CAP's three primary missions; it promotes understanding of aviation, space, cyber, and STEM."],
  ["Blues", "Common informal name for the Air Force-style service uniform combinations authorized by CAPR 39-1."],
  ["C/A1C", "Cadet Airman First Class."], ["C/Amn", "Cadet Airman."], ["C/SSgt", "Cadet Staff Sergeant, the first cadet NCO grade."], ["C/SrA", "Cadet Senior Airman."],
  ["Cadet", "A CAP member participating in the Cadet Program, generally from age 12 through 20."],
  ["Cadet Programs", "One of CAP's three primary missions; it develops youth through leadership, aerospace, fitness, and character."],
  ["CAP", "Civil Air Patrol, the congressionally chartered nonprofit corporation that serves as the civilian auxiliary of the U.S. Air Force when assigned."],
  ["Chain of Command", "The orderly line through which authority and responsibility pass."], ["COC", "Common abbreviation for chain of command."],
  ["Core Values", "Integrity, Volunteer Service, Excellence, and Respect."],
  ["Emergency Services", "One of CAP's three primary missions, including disaster relief, search and rescue, and support to communities and agencies."],
  ["Encampment", "A structured cadet activity emphasizing leadership, aerospace, fitness, teamwork, and the CAP environment."],
  ["Grade", "A member's rank, such as Cadet Airman or Captain; it is different from a duty position."],
  ["Group", "An intermediate echelon that may coordinate several squadrons within a wing."], ["NCO", "Noncommissioned officer."], ["NHQ", "Civil Air Patrol National Headquarters."],
  ["OCP", "Operational Camouflage Pattern, the currently authorized Air Force-style utility uniform addressed by CAPR 39-1 and its interim changes."],
  ["Region", "An organizational echelon that coordinates multiple wings."], ["Senior Member", "An adult CAP member serving outside the cadet membership category."],
  ["Squadron", "A local CAP unit where members normally meet and train."], ["Wing", "An organizational echelon generally corresponding to a state, the District of Columbia, or Puerto Rico."]
].map(([term, definition]) => ({ term, definition }));

const MODULES = [
  {
    id: "history", number: "01", title: "History of Civil Air Patrol", icon: "1941", time: "15 min",
    description: "Why CAP was created, its World War II service, and the organization's modern missions.",
    sections: [
      { title: "Why CAP was created", kicker: "Origins · 1941", body: ["Civil Air Patrol was established on December 1, 1941, just days before the United States entered World War II. Civilian aviation advocates had argued that private pilots and aircraft could contribute to national defense.", "Volunteers brought their aircraft, flying skills, and local knowledge. CAP members performed patrol, courier, transport, training, and other support missions while the armed forces concentrated on combat operations."], takeaway: "CAP began as citizens using aviation skills in service to the nation." },
      { title: "Coastal Patrol", kicker: "Wartime service", body: ["German submarines threatened shipping along the Atlantic and Gulf coasts. CAP coastal patrol crews flew from a network of bases to watch for submarines, survivors, and ships in distress.", "Some CAP aircraft were eventually authorized to carry bombs or depth charges. Their presence helped deter submarine activity, and the patrols demonstrated how organized civilian aviation could support national defense."], takeaway: "CAP coastal patrol was one part of a broader wartime support effort." },
      { title: "From war to auxiliary", kicker: "1946–1948", body: ["Congress granted Civil Air Patrol a federal charter in 1946. In 1948, Congress designated CAP as the civilian auxiliary of the newly created United States Air Force.", "Those actions helped move CAP from a temporary wartime organization to an enduring public-service institution. CAP remains a nonprofit corporation and serves as the Air Force auxiliary when assigned an Air Force mission."], takeaway: "CAP's postwar legal status shaped the organization cadets know today." },
      { title: "CAP today", kicker: "Three primary missions", body: ["Emergency Services supports communities and government partners through missions such as disaster relief, search and rescue, aerial imagery, communications, and mission support. Members qualify for specific jobs through training, evaluation, and supervised experience.", "Aerospace Education advances aviation, space, cyber, and STEM learning for CAP members and the public. Cadet Programs develops young people through leadership, aerospace, fitness, character, service, and progressively greater responsibility.", "The missions overlap. A cadet might learn aerospace principles, practice team leadership, qualify for emergency-services support, and use all three areas during a community mission."], cards: [["Emergency Services", "Prepared volunteers supporting communities and authorized missions."], ["Aerospace Education", "Aviation, space, cyber, and STEM learning."], ["Cadet Programs", "Leadership and character development for youth."]], takeaway: "The three missions reinforce one another through service, learning, and leadership." },
      { title: "Tell the story accurately", kicker: "History with evidence", body: ["CAP history includes remarkable service, but accurate leaders separate documented facts from legends. Use official CAP history resources, dates, and primary records before repeating a dramatic claim.", "Remember the sequence: established in 1941; wartime civilian aviation support; federally chartered in 1946; designated the Air Force auxiliary in 1948; modern service through three primary missions.", "When explaining CAP to a visitor, connect the past to the present: volunteers organized aviation skills for national service, and today's members continue that tradition through readiness, education, and youth development."], takeaway: "Know the dates, explain the purpose, and avoid exaggeration." }
    ],
    activity: { type: "timeline", title: "Mission timeline", items: [["1941", "CAP established", "Civil Air Patrol is established on December 1."], ["1942", "Coastal Patrol", "CAP begins coastal patrol operations during World War II."], ["1946", "Federal charter", "Congress grants CAP a federal charter."], ["1948", "Air Force auxiliary", "Congress designates CAP as the civilian auxiliary of the U.S. Air Force."], ["Today", "Three missions", "Emergency Services, Aerospace Education, and Cadet Programs."]] },
    sources: ["CAP History"],
    quiz: [
      { q: "When was Civil Air Patrol established?", options: ["December 1, 1941", "July 4, 1946", "September 18, 1947", "May 26, 1948"], answer: 0, why: "CAP was established on December 1, 1941." },
      { q: "What threat was a major focus of CAP coastal patrol?", options: ["Forest fires", "German submarines", "Airport congestion", "Weather balloons"], answer: 1, why: "Coastal patrol crews watched for German U-boats, survivors, and ships in distress." },
      { q: "Which event happened first?", options: ["CAP became the Air Force auxiliary", "CAP received a federal charter", "The Wright Brothers Award began", "OCP wear was authorized"], answer: 1, why: "CAP received its federal charter in 1946 and became the Air Force auxiliary in 1948." },
      { q: "Which list contains CAP's three primary missions?", options: ["Flying, drill, and uniforms", "Emergency Services, Aerospace Education, and Cadet Programs", "Search, rescue, and transport", "Leadership, fitness, and character"], answer: 1, why: "CAP organizes its work around Emergency Services, Aerospace Education, and Cadet Programs." },
      { q: "True or false: CAP's World War II service was limited only to coastal patrol.", options: ["True", "False"], answer: 1, why: "CAP volunteers performed several kinds of support work, including courier, transport, training, patrol, and other missions." }
    ]
  },
  {
    id: "core-values", number: "02", title: "Core Values & Cadet Oath", icon: "IVXE", time: "20 min",
    description: "Practice Integrity, Volunteer Service, Excellence, and Respect—and understand every promise in the oath.",
    sections: [
      { title: "Remember IVER", kicker: "Core Values memory aid", body: ["Use the letters I-V-E-R to recall the four CAP Core Values in order: Integrity, Volunteer Service, Excellence, and Respect. Say the letters aloud as “eye-ver,” then expand each letter into its full value.", "IVER helps you remember the Core Values; it does not replace memorizing the Cadet Oath. Connect each value to a visible action: tell the truth, serve willingly, improve the work, and protect every person's dignity."], cards: [["I · Integrity", "Do what is right, tell the truth, and own your actions."], ["V · Volunteer Service", "Put the mission, team, and community ahead of convenience."], ["E · Excellence", "Prepare carefully, accept feedback, and improve."], ["R · Respect", "Treat every person with dignity and professional courtesy."]], takeaway: "IVER: Integrity · Volunteer Service · Excellence · Respect." },
      { title: "Integrity", kicker: "Do what is right", body: ["Integrity means choosing honesty and moral courage even when no one is watching. A cadet reports mistakes, protects test integrity, and can be trusted with equipment and responsibility.", "Example: You accidentally damage squadron equipment. Report it promptly, explain what happened, and help make it right. Hiding the damage violates integrity."], takeaway: "Truthful accountability builds trust." },
      { title: "Volunteer Service", kicker: "Put service before self", body: ["Volunteer Service means willingly giving time, talent, and effort to help the team and community. It does not require ignoring safety or personal limits; it means looking beyond convenience.", "Example: Arrive prepared, help reset the meeting space, and assist a new cadet without waiting to be asked. Avoid taking credit for work you did not do."], takeaway: "Service asks: what does the mission need from me?" },
      { title: "Excellence", kicker: "Improve the standard", body: ["Excellence is a habit of disciplined improvement. It is not perfection. It means preparing carefully, learning from feedback, and completing duties to the best standard you can reach.", "Example: Practice drill before a performance and correct a recurring mistake. Rushing through a task because it is 'good enough' does not demonstrate excellence."], takeaway: "Prepare, perform, review, improve." },
      { title: "Respect", kicker: "Value every person", body: ["Respect means treating people with dignity and fairness. Courtesy, listening, professional language, and care for boundaries all show respect—regardless of grade or position.", "Example: Correct a teammate privately and constructively. Humiliating someone, hazing, or dismissing a concern violates respect."], takeaway: "Standards and dignity belong together." },
      { title: "The Cadet Oath", kicker: "A promise with actions", oath: true, body: ["The oath is not simply something to memorize. Each phrase describes a commitment: faithful service, regular attendance, active participation, lawful obedience, proper uniform wear, rapid growth, and readiness to serve.", "Learn it in short phrase groups. Read one phrase, cover it, say it, check it, then connect it to the next phrase. Practice from the beginning after adding each new group so the transitions become automatic.", "Cadets should ask questions when an instruction is unclear or appears unsafe. Following the chain of command never removes the duty to act safely and ethically."], steps: ["Serve faithfully in the Cadet Program", "Attend meetings regularly", "Participate actively in unit activities", "Obey officers", "Wear the uniform properly", "Advance education and training rapidly", "Prepare to serve community, state, and nation"], takeaway: "IVER recalls the Core Values; phrase-by-phrase practice builds the Cadet Oath." }
    ],
    activity: { type: "oath", title: "Explore the Cadet Oath", items: [["serve faithfully", "Be dependable and uphold the Cadet Program's purpose and values."], ["attend meetings regularly", "Show up consistently so your team can rely on you and your skills can grow."], ["participate actively", "Engage, ask questions, practice, and contribute—not merely occupy a seat."], ["obey my officers", "Follow lawful, safe instructions through the chain of command and seek clarification when needed."], ["wear my uniform properly", "Represent CAP professionally and use the current uniform regulation."], ["advance my education and training rapidly", "Take ownership of steady progress without sacrificing understanding or integrity."], ["be of service", "Prepare your skills and character to help your community, state, and nation."]] },
    sources: ["Cadet Character Resources", "CAPR 60-1"],
    quiz: [
      { q: "You damage squadron equipment and nobody sees it. Which action best demonstrates Integrity?", options: ["Put it back quietly", "Blame normal wear", "Report the damage and help make it right", "Wait to see if someone notices"], answer: 2, why: "Integrity includes truthful accountability even when admitting a mistake is uncomfortable." },
      { q: "Which Core Value is most directly shown by helping a new cadet learn without being asked?", options: ["Volunteer Service", "Excellence", "Integrity", "Respect only"], answer: 0, why: "Willingly contributing time and effort to help the team demonstrates Volunteer Service." },
      { q: "Excellence means never making a mistake.", options: ["True", "False"], answer: 1, why: "Excellence is disciplined preparation and improvement, not impossible perfection." },
      { q: "What is the difference between attending and participating actively?", options: ["There is no difference", "Active participation means engaging, practicing, and contributing", "Active participation means speaking the most", "Attendance matters only for promotion"], answer: 1, why: "The oath asks cadets to contribute to activities, not simply be present." },
      { q: "Which response best demonstrates Respect during a correction?", options: ["Embarrass the cadet so others learn", "Ignore the issue", "Correct privately, clearly, and constructively", "Use rank to end discussion"], answer: 2, why: "Respect preserves dignity while still supporting standards." }
    ]
  },
  {
    id: "chain-of-command", number: "03", title: "Chain of Command", icon: "COC", time: "20 min",
    description: "Follow Northshore's path from squadron to National Headquarters and learn when to use each chain.",
    sections: [
      { title: "Why a chain exists", kicker: "Authority + responsibility", body: ["A chain of command gives questions, decisions, information, and accountability an orderly route. For a routine matter, begin with the lowest leader who owns the work. Give that leader enough time and information to help before moving upward.", "Move to the next level when the first leader cannot resolve the issue, is unavailable, is personally involved in the concern, or directs you upward. Do not skip levels merely to obtain a preferred answer.", "Urgent safety, medical, abuse, bullying, harassment, or cadet-protection concerns are different. Contact any trusted senior member or emergency authority as appropriate; never delay immediate help to preserve routine routing."], takeaway: "Use the chain to solve problems—never to block safety reporting." },
      { title: "Tango Flight chain", kicker: "Start closest to the work", body: ["For normal Tango Flight questions, begin with your element leader when one is assigned, then the Tango Flight Sergeant, C/MSgt Jason How. The flight sergeant manages standards, accountability, and the work of the flight.", "Next is Tango Flight Commander, C/SMSgt Liam Johnson. The flight commander sets direction for the flight and coordinates with the cadet command staff.", "Use a complete request: identify yourself, briefly state the issue, explain what you have already tried, and say what decision or help you need."], takeaway: "Routine path: element leader → flight sergeant → flight commander." },
      { title: "Northshore cadet staff", kicker: "Flight to cadet command", body: ["Above the flight is the Cadet Deputy Commander for Operations, C/Capt Tieman Green, who coordinates operational cadet activities. The Cadet Deputy Commander for Support, C/Capt Kiyomi Hakuno, coordinates support functions assigned by the unit.", "The Cadet Commander is C/Capt Daniel Taylor. The cadet commander leads the cadet corps under authority delegated by the senior-member command team.", "Grade and duty position are different. C/Capt is a grade; Cadet Commander or Deputy Commander is the member's current job. Duty positions rotate, so confirm this roster when staff changes."], takeaway: "Know both the person's grade and the job they currently perform." },
      { title: "Senior-member command", kicker: "Adult supervision and command", body: ["Northshore's Deputy Commander for Cadets is Capt Daniel Taylor. This officer supervises the Cadet Program and mentors cadet staff. The Squadron Commander is Capt Carlos Jiminez and retains command responsibility for the entire squadron.", "The organizational chain continues through Northwest Group Commander Lt Col Thomas Wittenberg, Washington Wing Commander Col Sid Wiggs, Pacific Region Commander Col Brett D. Dolnick, and National Commander Maj Gen Regena M. Aye.", "Cadet leaders exercise real leadership, but senior members remain responsible for safety, supervision, regulatory compliance, and command decisions."], takeaway: "Cadet leadership operates within senior-member command and supervision." },
      { title: "Roster and verification", kicker: "Updated 21 September 2026", body: ["National and Washington Wing commanders were checked against their official CAP leadership pages. The remaining region, group, squadron, and cadet duty positions reflect the Northshore roster supplied for this learning center.", "Leadership changes. Before using a name for a formal email, report, ceremony, or introduction, check the current squadron roster or official echelon directory. If a page and staff direction disagree, ask staff which source is current."], takeaway: "Learn the structure permanently; verify the names regularly." }
    ],
    activity: { type: "hierarchy", title: "Northshore chain roster · 21 September 2026", items: SITE_CONFIG.leadership.map((x) => [x.position, x.name, `${x.organization}. ${x.note}`]) },
    sources: ["CAPR 30-1", "CAP National Command Team", "Pacific Region Staff", "Washington Wing Staff", "Northshore Composite Squadron"],
    quiz: [
      { q: "Put the organizational levels in order from local to national.", options: ["Squadron → Group → Wing → Region → National", "Squadron → Wing → Group → National → Region", "Group → Squadron → Region → Wing → National", "Squadron → Region → Wing → Group → National"], answer: 0, why: "Northshore's path is Squadron, Northwest Group, Washington Wing, Pacific Region, then National Headquarters." },
      { q: "What is the best first step for a routine question about tonight's assigned task?", options: ["Contact National Headquarters", "Ask the lowest appropriate leader in your chain", "Post the question publicly", "Skip the task"], answer: 1, why: "Routine issues should normally begin with the leader closest to the work." },
      { q: "Grade and duty position mean the same thing.", options: ["True", "False"], answer: 1, why: "Grade is rank; duty position is the job a member currently performs." },
      { q: "Who is listed as the Washington Wing Commander in this roster?", options: ["Col Sid Wiggs", "Col Brett D. Dolnick", "Lt Col Thomas Wittenberg", "Capt Carlos Jiminez"], answer: 0, why: "Col Sid Wiggs is listed by the official Washington Wing staff directory. Leadership names should still be re-checked regularly." },
      { q: "Should a cadet delay reporting an urgent safety problem to preserve the routine chain?", options: ["Yes", "No"], answer: 1, why: "Immediate safety and protection concerns should use the appropriate direct route without unnecessary delay." }
    ]
  },
  {
    id: "customs", number: "04", title: "Customs & Courtesies", icon: "SAL", time: "25 min",
    description: "Build confident habits for saluting, forms of address, reporting, formations, and ceremonies.",
    sections: [
      { title: "Saluting: when and where", kicker: "Recognition and respect", body: ["When outdoors in a CAP uniform, cadets normally salute CAP senior-member officers and cadet officers when recognition is practical. Begin the salute early enough for the officer to return it—roughly six paces is a useful training cue—and combine it with a professional greeting such as “Good evening, Ma'am.” Hold the salute until it is returned or acknowledged.", "Indoors, do not normally salute unless formally reporting or participating in a ceremony that calls for it. When in formation, the person in command normally exchanges salutes for the formation; individual members remain at the commanded position. Do not render a walking salute while running, eating, or doing something unsafe—pause or use a courteous verbal greeting as appropriate.", "Salute outdoors during prescribed honors to the flag and anthem. If you are unsure whether a person is an officer, a courteous greeting is always appropriate; ask a leader afterward so you recognize the insignia next time."], cards: [["Outdoors + uniform", "Recognize the officer, salute smartly, and give the greeting of the day."], ["Indoors", "Normally no salute except formal reporting or a prescribed ceremony."], ["In formation", "Follow commands; the formation commander handles the exchange."], ["Safety first", "Never force a salute when doing so would be unsafe."]], takeaway: "See, recognize, salute, greet—and keep the situation safe." },
      { title: "Morning colors, evening colors, and anthem", kicker: "Honor the flag", body: ["If you are outdoors and not in formation when the National Anthem or To the Color begins, stop, face the flag if visible—or face the music if it is not—and render the salute in uniform. Hold the salute through the final note. If in formation, remain with the formation and follow the commands of the person in charge.", "For evening colors, Retreat may sound before To the Color. At the first note of Retreat, face the flag or music and stand at parade rest unless directed otherwise. At the first note of To the Color, come to attention and render the salute when prescribed. Morning colors may use Reveille with a local flag-raising sequence; follow the published ceremony and commands at the activity.", "Indoors, stop respectfully, face the flag or music as appropriate, and stand at attention; do not improvise an indoor salute unless the ceremony or reporting procedure requires one. Outdoors in civilian clothes, stand at attention and place the right hand over the heart for the anthem unless another rule applies to you."], steps: ["Stop talking and moving", "Face the flag; if unseen, face the music", "Assume the correct position for the signal", "Salute when prescribed", "Hold through the final note", "Resume only after honors end"], takeaway: "Stop · face · honor · hold through the last note." },
      { title: "Forms of address", kicker: "Use the right professional title", body: ["Address officers as Sir or Ma'am, or by grade and last name when appropriate. A cadet officer may be addressed as Sir/Ma'am or Cadet Lieutenant, Cadet Captain, and so on. A senior-member officer may be addressed as Lieutenant, Captain, Major, Colonel, or Sir/Ma'am.", "For NCOs, use Sergeant and last name unless a more specific title is customary. Chief is appropriate for a chief master sergeant. At Northshore, staff may use Senior for an adult member whose grade is unknown or who is addressed locally as “Senior Member”; when uncertain, use Sir/Ma'am and ask politely.", "Duty position is not grade. “Flight Sergeant” and “Cadet Commander” name jobs; C/MSgt and C/Capt name grades. In a formal introduction, use the grade and full name, then the duty position."], cards: [["Sir / Ma'am", "Officers, or a respectful default when local practice calls for it."], ["Sergeant", "Cadet or senior-member NCOs below chief master sergeant."], ["Chief", "A chief master sergeant."], ["Senior", "A Northshore/local form when instructed; ask if the member's preferred title is unclear."]], takeaway: "Use grade or the correct title—never guess casually in a formal setting." },
      { title: "Calling the room to attention", kicker: "Recognize the senior officer", body: ["When the senior officer who outranks everyone already present enters a room, the first person who sees that officer may call “Room, ATTENTION” in a clear command voice. Everyone who is able stops, stands at attention, faces appropriately, and remains silent until the officer says “Carry on,” “As you were,” or gives another direction.", "Do not repeatedly call the room when the senior officer is already present, when a class or meeting is actively under another leader's control, or when local instructions say the room should remain working. The ranking person present or instructor may designate a different procedure.", "Safety and mission needs take priority. Do not call a room to attention where sudden movement would create a hazard, interrupt urgent operations, or interfere with medical care. Northshore staff should demonstrate when this custom applies in the squadron's meeting spaces."], takeaway: "Notice the senior officer, use one clear command, then wait for direction." },
      { title: "Professional responses", kicker: "Short, clear, accountable", body: ["Use a respectful title with direct answers: “Yes, Sir,” “No, Ma'am,” “Yes, Sergeant,” or “No, Chief.” If you did not hear or understand, say so: “Sir, please repeat the instruction,” or “Sergeant, I do not understand step two.” A clear question is better than pretending.", "Useful accountability responses include “No excuse, Sir,” when you are acknowledging a failure without shifting blame, and “Ma'am, I do not know, but I will find out,” when you lack an answer. Do not use “no excuse” to conceal a safety issue, relevant fact, or honest explanation the leader needs to make a decision.", "Repeat critical details when appropriate: “Yes, Sergeant—formation at 1900 by the south door.” If you cannot comply safely or lawfully, state the concern immediately and seek clarification from an appropriate leader."], cards: [["Yes / No", "Answer directly, followed by Sir, Ma'am, Sergeant, Chief, or the locally directed title."], ["Please repeat", "Use when you did not hear the instruction."], ["I do not understand", "Identify the part needing clarification."], ["I do not know", "Add: “but I will find out,” then follow through."], ["No excuse", "Own the failure; never use it to hide a material safety fact."]], takeaway: "Be brief, respectful, truthful, and complete enough for the leader to act." },
      { title: "Reporting", kicker: "A deliberate sequence", body: ["Reporting procedures vary with the setting and whether you are indoors, outdoors, or in formation. A common office sequence is to knock once if appropriate, enter when directed, approach and halt about two paces away, salute when required, make the reporting statement, and remain at attention unless told otherwise.", "Use a concise statement such as “Sir, Cadet Airman Smith reports as ordered,” or state the purpose of the visit. Listen fully, answer with the proper form of address, repeat instructions when helpful, and ask questions before departing.", "When dismissed, acknowledge the dismissal, take one step backward if space permits, salute if the reporting procedure requires it, execute the appropriate facing movement, and depart professionally. Practice the exact local sequence with an instructor."], steps: ["Knock if appropriate", "Enter when directed", "Approach and halt about two paces away", "Salute when required", "Report or state your purpose", "Listen, answer, and clarify", "Acknowledge dismissal", "Salute, face, and depart when appropriate"], takeaway: "Practice the sequence slowly, then make every word and movement deliberate." }
    ],
    activity: { type: "scenario", title: "Saluting scenario trainer", prompt: "You are outdoors in uniform. A CAP captain approaches and neither of you is in formation. What is the best response?", options: ["Ignore the officer", "Salute and give the greeting of the day", "Stand at parade rest", "Remove your cover"], answer: 1, feedback: "Salute the officer and offer an appropriate greeting. Keep moving unless the situation calls for you to stop." },
    sources: ["CAPP 60-33", "CAPR 60-1"],
    quiz: [
      { q: "You are walking outdoors in uniform and a CAP captain approaches. What should you normally do?", options: ["Ignore them", "Salute and offer the greeting of the day", "Remove your cover", "Stand at parade rest"], answer: 1, why: "Cadets normally exchange salutes with commissioned officers outdoors when the situation is appropriate." },
      { q: "What should normally happen when the senior officer who outranks everyone present enters an appropriate room?", options: ["Everyone keeps talking", "The first person who sees the officer calls Room, ATTENTION", "Everyone salutes while seated", "The newest cadet leaves"], answer: 1, why: "One clear call brings the room to attention, unless local instructions, an active class, safety, or mission conditions call for another procedure." },
      { q: "When the U.S. flag is not visible during an outdoor anthem, what direction is generally used?", options: ["Face north", "Face the music", "Face the nearest officer", "Remain facing forward in every situation"], answer: 1, why: "Individuals generally face the music when the flag is not visible, while following formation commands if in formation." },
      { q: "Which response is best when you do not know an answer?", options: ["Guess confidently", "Stay silent", "Sir/Ma'am, I do not know, but I will find out", "Change the subject"], answer: 2, why: "Professional responses are brief, respectful, truthful, and followed by action." },
      { q: "Which source should control detailed CAP drill and ceremonial procedures?", options: ["A social media clip", "CAPP 60-33 and current official guidance", "A movie", "An unofficial forum"], answer: 1, why: "Use current official CAP publications and supervised instruction." }
    ]
  },
  {
    id: "promotions", number: "05", title: "Cadet Promotions", icon: "↑", time: "20 min",
    description: "Explore the Phase I progression from Cadet Airman Basic through the Wright Brothers Award.",
    sections: [
      { title: "Phase I: The Learning Phase", kicker: "Build foundations", body: ["Phase I introduces followership, self-discipline, CAP knowledge, drill, fitness, character, and aerospace. New cadets begin as Cadet Airman Basic and advance by completing achievement requirements and demonstrating readiness for greater responsibility.", "Promotion is more than passing online tests. Participation, performance, character, fitness, drill, and command approval all matter under the current cadet program rules."], takeaway: "Own your progress and ask staff which requirement comes next." },
      { title: "Curry Achievement", kicker: "Achievement 1 · C/Amn", body: ["The Curry Achievement is named for Maj Gen John F. Curry, CAP's first national commander. Completion earns the grade of Cadet Airman and marks the first promotion.", "Typical categories include introductory leadership learning, character participation, fitness participation, active participation, the Cadet Oath, and the required drill performance. Confirm the current checklist in the Cadet Super Chart and eServices."], takeaway: "Curry proves you can begin building reliable cadet habits." },
      { title: "Arnold & Feik", kicker: "Achievements 2–3", body: ["The Arnold Achievement honors Gen Henry H. 'Hap' Arnold and leads to Cadet Airman First Class. The Feik Achievement honors aviation pioneer and CAP leader Mary Feik and leads to Cadet Senior Airman.", "Each achievement continues leadership, aerospace, character, fitness, drill, active participation, and time-in-grade requirements as shown on the current Super Chart. Exact test modules and standards can change, so verify before planning."], takeaway: "Phase I alternates learning, practice, and increasing responsibility." },
      { title: "Wright Brothers Award", kicker: "Milestone · C/SSgt", body: ["The Wright Brothers Award marks completion of Phase I and promotion to Cadet Staff Sergeant when all current requirements are completed and the promotion is approved.", "It includes controlled milestone testing and a drill and ceremonies performance component. Milestone exams are administered through the squadron under current CAP procedures. The award also opens Phase II, where cadets begin serving as NCOs and leading teams."], takeaway: "The first milestone marks the shift from learning followership to practicing NCO leadership." },
      { title: "Plan your next promotion", kicker: "One requirement at a time", body: ["Open eServices and the current Cadet Super Chart before planning. Identify the exact leadership or aerospace module, drill test, fitness participation, character requirement, time-in-grade date, and any special requirement associated with the achievement.", "Ask staff early how your squadron schedules drill tests, milestone exams, promotion reviews, and approvals. Completing an online task at the last minute does not guarantee every in-person requirement can be administered that night.", "Keep a simple checklist with the source and completion date for each item. Continue participating and practicing after the boxes are checked—the purpose of promotion is readiness for greater responsibility, not merely collecting grade."], steps: ["Check eServices and the current Super Chart", "List every academic and in-person requirement", "Confirm the earliest eligibility date", "Schedule drill or milestone testing", "Ask for feedback before the promotion review", "Verify the promotion posted correctly"], takeaway: "Plan from official requirements, schedule early, and build the skill behind the grade." }
    ],
    activity: { type: "ladder", title: "Phase I promotion ladder", items: [["C/AB", "Cadet Airman Basic", "Starting grade"], ["C/Amn", "Curry Achievement", "Achievement 1"], ["C/A1C", "Arnold Achievement", "Achievement 2"], ["C/SrA", "Feik Achievement", "Achievement 3"], ["C/SSgt", "Wright Brothers Award", "Phase I milestone"]] },
    sources: ["Cadet Super Chart", "CAPR 60-1", "CAPP 60-34"],
    quiz: [
      { q: "Which achievement normally results in promotion to Cadet Airman?", options: ["Arnold", "Curry", "Feik", "Wright Brothers"], answer: 1, why: "Achievement 1, named for Maj Gen John F. Curry, leads to Cadet Airman." },
      { q: "Which achievement is associated with Cadet Senior Airman?", options: ["Curry", "Arnold", "Feik", "Wright Brothers"], answer: 2, why: "The Feik Achievement is the third Phase I achievement and leads to Cadet Senior Airman." },
      { q: "What does the Wright Brothers Award mark?", options: ["Joining CAP", "Completion of Phase I and promotion to C/SSgt when requirements are met", "Completion of encampment", "Becoming a cadet officer"], answer: 1, why: "The Wright Brothers milestone completes Phase I and begins cadet NCO service." },
      { q: "Passing online tests is the only requirement for promotion.", options: ["True", "False"], answer: 1, why: "The program also considers participation, drill, fitness, character, performance, and approval under current rules." },
      { q: "Where should a cadet check exact current achievement requirements?", options: ["An old handout", "The current Cadet Super Chart, eServices, and CAPR 60-1", "A social post", "A uniform catalog"], answer: 1, why: "Official current sources control because requirements and materials can change." }
    ]
  },
  {
    id: "grooming", number: "06", title: "Hair & Grooming", icon: "39-1", time: "15 min",
    description: "Learn how to find and apply current CAPR 39-1 grooming standards without relying on outdated rules.",
    sections: [
      { title: "Start with the right rule", kicker: "CAPR 39-1 + ICLs", body: ["Grooming rules depend on the uniform category, and CAPR 39-1 may be supplemented by interim change letters. Open the current publication index before relying on a measurement or an older checklist.", "This training module intentionally does not repeat numerical limits without a verified paragraph. Ask staff to review the current text and illustrations with you."], takeaway: "Never turn a remembered number into a regulation." },
      { title: "Masculine standards", kicker: "Professional appearance", body: ["Review the current provisions for hair appearance, bulk, length, tapered appearance, contact with ears or collar, sideburns, mustaches, and other facial hair.", "The standard is more specific than simply 'neat.' Use the current paragraph and figures, especially when a question involves measurement, medical or religious accommodation, or a style not clearly shown."], takeaway: "Use the published standard, not personal preference." },
      { title: "Feminine standards", kicker: "Professional appearance", body: ["Review the current provisions for hair length, bulk, bangs, ponytails, braids, buns, accessories, and styles worn in uniform. Authorized options and exact limits may be updated by interim change.", "Hair must also allow required headgear and safety equipment to be worn correctly. Use CAPR 39-1 and current changes rather than assuming another service's rule automatically applies."], takeaway: "A professional result can include multiple authorized styles." },
      { title: "Color, accessories, and judgment", kicker: "Consistent and mission-ready", body: ["Hair color, accessories, cosmetics, nails, jewelry, and related appearance topics are addressed by uniform category and current policy. Conservative or professional wording is not permission to invent local measurements.", "Leaders should correct standards consistently, privately, and respectfully. Cadets should ask for the source paragraph when a rule is unclear."], takeaway: "Cite the rule and preserve dignity during corrections." },
      { title: "Run a grooming check", kicker: "Before leaving home", body: ["Check grooming in the same uniform and headgear you will wear. Look from the front, sides, and back; confirm hair remains controlled during normal movement and that the cover sits correctly without forcing the style out of standard.", "Then check facial hair, sideburns, cosmetics, nails, jewelry, and hair accessories against the current paragraph for your uniform category. Mission or safety equipment may add restrictions even when an item is otherwise authorized.", "If corrected, ask for the source and fix the issue without argument. Leaders should explain the standard privately and distinguish a published requirement from personal preference. Medical and religious accommodations follow formal processes and should be handled respectfully."], steps: ["Open the current CAPR 39-1 and ICL package", "Select the correct uniform category", "Check hair from front, sides, and back", "Put on required headgear and safety equipment", "Verify facial hair, cosmetics, nails, jewelry, and accessories", "Ask staff about any unclear or accommodated standard"], takeaway: "Inspect the complete appearance under the rule that applies to the uniform you are wearing." }
    ],
    activity: { type: "checklist", title: "Grooming standard finder", items: [["Hair shape and bulk", "Find the paragraph for your uniform category; verify any current ICL."], ["Ears, collar, and taper", "Use the exact text and figures rather than a remembered rule."], ["Ponytails, braids, and buns", "Confirm style, length, bulk, accessory, and headgear provisions."], ["Sideburns and facial hair", "Check the current grooming section and any accommodation policy."], ["Color and accessories", "Confirm authorized colors, size limits, and placement in the current publication."]] },
    sources: ["CAPR 39-1", "OCP Information"],
    quiz: [
      { q: "Where should you verify a numerical grooming limit?", options: ["A friend's memory", "The current CAPR 39-1 paragraph and attached changes", "A recruiting poster", "Any Air Force video"], answer: 1, why: "Exact limits must come from the current CAP publication and its interim changes." },
      { q: "CAP automatically adopts every Air Force grooming rule without CAP guidance.", options: ["True", "False"], answer: 1, why: "CAP members must follow CAP-authorized standards; do not assume another service's rule automatically applies." },
      { q: "What should a leader do when making a grooming correction?", options: ["Invent a stricter local limit", "Correct publicly", "Use the source, be consistent, and preserve dignity", "Ignore every issue"], answer: 2, why: "Accurate, respectful correction supports both standards and the Core Values." },
      { q: "Why should interim change letters be checked?", options: ["They may modify the base regulation", "They are only historical", "They are optional", "They apply only to pilots"], answer: 0, why: "An interim change letter can add or alter requirements before the base publication is rewritten." },
      { q: "Which factor can affect whether a hairstyle works in uniform?", options: ["Whether required headgear and safety equipment fit correctly", "Whether it is popular", "Whether another cadet wears it", "Whether it appears online"], answer: 0, why: "Uniform grooming must support correct wear of required headgear and mission equipment." }
    ]
  },
  {
    id: "uniforms", number: "07", title: "Uniform Regulations", icon: "UOD", time: "20 min",
    description: "Inspect Blues and OCP uniforms using the current regulation, figures, tables, and interim changes.",
    sections: [
      { title: "Uniform mindset", kicker: "Service, not costume", body: ["The uniform identifies you as a CAP member and communicates attention to detail. Wear only authorized items, in the authorized combination, and maintain a clean, serviceable appearance.", "CAPR 39-1, its attached interim change letters, and approved supplements control. Product photos, old handouts, and another service's habits do not replace them."], takeaway: "Check the whole uniform before focusing on one insignia." },
      { title: "Air Force-style service uniform", kicker: "Blues", body: ["Build the uniform from the authorized combination: correct shirt or blouse, trousers or skirt, belt, footwear, headgear when required, insignia, nameplate, ribbons or badges as authorized, and appropriate outerwear.", "Placement details vary by garment, grade, and item. Use the current CAPR 39-1 figures and tables for measurements. Cadets who do not yet have every optional item should prioritize the required, properly fitted basics."], takeaway: "Correct fit and placement are part of military professionalism." },
      { title: "Operational Camouflage Pattern", kicker: "OCP", body: ["CAP's OCP authorization is governed by CAPR 39-1 and the applicable interim change letter. Confirm the coat, trousers, patrol cap, Tan 499 shirt and belt, coyote-brown boots, authorized tapes, grade, and currently authorized patches.", "The official OCP FAQ is helpful but states that it is not regulatory. When the FAQ and a memory differ, return to the ICL and regulation. Do not mix incompatible uniform variants or attachment methods when current guidance prohibits it."], takeaway: "OCP details are changing—always check the latest official package." },
      { title: "Accessories and final inspection", kicker: "From headgear to footwear", body: ["Review headgear, outerwear, jewelry, watches, sunglasses, gloves, bags, and other accessories as part of the complete uniform. Authorization can depend on the uniform and setting.", "Use a consistent inspection: headgear; grooming; collar and insignia; tapes or nameplate; pockets and patches; belt; trousers; footwear; then authorized accessories. Ask a trained leader to verify anything uncertain."], takeaway: "A repeatable inspection sequence catches preventable errors." },
      { title: "Prepare, travel, and recover", kicker: "Uniform care cycle", body: ["The night before, check the meeting uniform, schedule, and weather. Lay out every required item; clean and polish footwear as appropriate; remove loose threads; check closures, pockets, insignia, nameplate, ribbons, tapes, and patches against the current figure or table.", "Transport the uniform so it remains presentable. Carry small authorized supplies for predictable problems, such as a lint roller, spare fasteners, or shoe-care cloth. Do not make a rushed placement change from memory just before formation—use the official measurement.", "After the activity, empty pockets, clean and dry items correctly, identify damage, and store garments and insignia so the next inspection starts from a known condition. Report lost organizational equipment promptly."], steps: ["Confirm the uniform of the day", "Lay out every required item", "Inspect from headgear to footwear", "Measure placement from the current figure", "Pack for weather and minor repairs", "Clean, inventory, and store after use"], takeaway: "A sharp uniform is the result of a repeatable preparation and care routine." }
    ],
    activity: { type: "uniform", title: "What's wrong with this uniform?", prompt: "Select every item that should be verified before this notional OCP uniform is worn.", items: [["Name and CAP tapes", "Confirm required tapes, placement, color, and attachment method."], ["Grade insignia", "Confirm the correct grade, placement, and attachment method for the member."], ["Unit or higher-HQ patch", "Confirm the patch is currently authorized and approved for OCP wear."], ["Boots and belt", "Confirm coyote-brown boots and the current Tan 499 belt requirement."], ["Accessories", "Remove unauthorized items and verify any watch, eyewear, bag, or outerwear."]] },
    sources: ["CAPR 39-1", "OCP Information"],
    quiz: [
      { q: "Which source controls CAP uniform wear?", options: ["A vendor catalog", "CAPR 39-1 with current ICLs and approved supplements", "A movie", "Any Air Force checklist"], answer: 1, why: "Current CAP publications control CAP uniform wear." },
      { q: "The official OCP FAQ describes itself as regulatory.", options: ["True", "False"], answer: 1, why: "The FAQ says it is for reference and that the ICL and CAPR 39-1 control." },
      { q: "Which item belongs in a complete uniform inspection?", options: ["Only the shirt", "Only insignia", "Headgear through footwear plus authorized accessories", "Only the most visible error"], answer: 2, why: "A systematic head-to-toe check catches fit, placement, condition, and accessory issues." },
      { q: "May any squadron patch be placed on an OCP uniform?", options: ["Yes, every squadron patch is automatically authorized", "No; verify the patch is currently approved and authorized", "Only if it is colorful", "Only cadet officers may wear one"], answer: 1, why: "Current OCP guidance limits patches and requires applicable approval." },
      { q: "What should you do when an exact insignia measurement is uncertain?", options: ["Estimate", "Copy a friend", "Use the current CAPR 39-1 figure or table and ask staff", "Leave every insignia off"], answer: 2, why: "Exact placement should be verified from the current official illustration or text." }
    ]
  }
];
